#!/bin/bash

##### Set paths here

ROOT_DIR="/home/porchard/improving_enhancer_definitions"
SCRIPT_DIR="${ROOT_DIR}/scripts" # directory where all scripts are kept
GENE_LIST="${ROOT_DIR}/current_definitions/genes.txt" # one gene per line. chromosome, start, end, gene_id
CHROM_HMM_DIR="${ROOT_DIR}/ENCODE_chromhmm" # *HMM.bed.gz files
DNASE="${ROOT_DIR}/ENCODE_dnase/wgEncodeAwgDnaseMasterSites.bed.gz" # single file, from UCSC



##### generate the enhancer lists, using chrom_hmm w/ and without the dnase, extending and not

# with dnase, extending 2000 bp
Rscript ${SCRIPT_DIR}/generate_enhancer_list.R --genes $GENE_LIST --dnase $DNASE --tissue_threshold_dnase 2 --chrom_hmm_directory $CHROM_HMM_DIR --extension 2000 --out chromhmm_dnase.2000.enhancers

# without dnase, extending 2000 bp
Rscript ${SCRIPT_DIR}/generate_enhancer_list.R --genes $GENE_LIST --chrom_hmm_directory $CHROM_HMM_DIR --extension 2000 --out chromhmm.2000.enhancers

# with dnase, not extending
Rscript ${SCRIPT_DIR}/generate_enhancer_list.R --genes $GENE_LIST --dnase $DNASE --tissue_threshold_dnase 2 --chrom_hmm_directory $CHROM_HMM_DIR --extension 1 --out chromhmm_dnase.0.enhancers

# without dnase, not extending
Rscript ${SCRIPT_DIR}/generate_enhancer_list.R --genes $GENE_LIST --chrom_hmm_directory $CHROM_HMM_DIR --extension 1 --out chromhmm.0.enhancers
