ruan_2015:
	@bash ruan_2015.commands

motifs:
	bash find_motifs.commands

thurman: dnase_thurman.interactions.gz
dnase_thurman.interactions.gz :
	bash ../scripts/extract_thurman_interactions.sh

fantom: fantom.interactions.gz
fantom.interactions.gz :
	bash ../scripts/extract_fantom_interactions.sh
